dist: trusty
sudo: required
language: generic
os:
 - linux
 - osx
 
# Only test direct pushes to master
#
branches:
  only: 
    - master
  
before_install:
   - cd $HOME
   - git clone --recursive https://github.com/noseglasses/Leidokos-Testing.git
   - Leidokos-Testing/travis/before_install.sh

script: skip
    
jobs:
  include:
    - stage: test
      script:
         - cd $HOME
         - mkdir ktest
         - cd ktest
         - $HOME/Leidokos-Testing/travis/test_kaleidoscope_module.sh
         - cd /home/travis/ktest/firmware/1/build
         - ls -l
         - nm -C kaleidoscope.so
         - nm -C _kaleidoscope.so
         
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
    
cache:
ccache: true
